# Generated by Django 5.1.3 on 2024-11-20 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre del Clientes')),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Product')),
                ('marca', models.CharField(max_length=50, unique=True)),
                ('caracteristicas_categoria', models.CharField(choices=[('Comidas', 'Comidas'), ('Varios', 'Varios'), ('Bebidas', 'Bebidas'), ('Limpieza', 'Limpieza'), ('Ropa', 'Ropa')], max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, help_text='ingresa valores con decimales', max_digits=10, verbose_name='Precio')),
                ('cantidad_stock', models.IntegerField(verbose_name='Cantidad de stock')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_elaboracion', models.DateField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
    ]
